# Site settings
title: 符海飞的Jekyll博客
email: my@fuhaifei.xyz
description: 符海飞的Jekyll博客
github_username:  turkey321
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 9
paginate_path: "page:num"
