# Site settings
title: jekyll_blog
email: my@fuhaifei.xyz
description: 符海飞的个人博客

github_username:  turkey321
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 9
paginate_path: "page:num"

