# Site settings
title: jekyll_blog
email: my@fuhaifei.xyz
description: 符海飞的个人博客
baseurl: "/jekyll_blog/"
url:"http://www.fuhaifei.xyz"

github_username:  turkey321
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

paginate: 4
paginate_path: "page:num"

